export type GalleryImage = {
  id: string
  src: string
  alt: string
  featured?: boolean
  layout?: "default" | "wide" | "tall" | "large"
}

export const galleryImages: GalleryImage[] = [
  { id: "01", src: "/images/gallery/gallery-01.png", alt: "SOS coaches leading a youth training session outdoors", featured: true, layout: "large" },
  { id: "02", src: "/images/gallery/gallery-02.png", alt: "Young athletes lined up during an SOS practice", featured: true },
  { id: "03", src: "/images/gallery/gallery-03.png", alt: "Youth soccer players listening to coach instructions", featured: true, layout: "tall" },
  { id: "04", src: "/images/gallery/gallery-04.png", alt: "SOS training session on the field with coaches and players" },
  { id: "05", src: "/images/gallery/gallery-05.png", alt: "Community gathering during an SOS program event" },
  { id: "06", src: "/images/gallery/gallery-06.png", alt: "Coaches and youth athletes on the soccer field" },
  { id: "07", src: "/images/gallery/gallery-07.png", alt: "Group huddle during SOS mentorship session", featured: true, layout: "wide" },
  { id: "08", src: "/images/gallery/gallery-08.png", alt: "Youth players in team jerseys at practice" },
  { id: "09", src: "/images/gallery/gallery-09.png", alt: "SOS community session with diverse young athletes" },
  { id: "10", src: "/images/gallery/gallery-10.png", alt: "Training drills on the grass with SOS participants" },
  { id: "11", src: "/images/gallery/gallery-11.png", alt: "Young players gathered for coaching instructions" },
  { id: "12", src: "/images/gallery/gallery-12.png", alt: "SOS program moment with mentors and youth" },
  { id: "13", src: "/images/gallery/gallery-13.png", alt: "Team activity on the field during SOS training" },
  { id: "14", src: "/images/gallery/gallery-14.png", alt: "703 Warriors team huddle with coaches", featured: true, layout: "wide" },
  { id: "15", src: "/images/gallery/gallery-15.png", alt: "Youth athletes lined up for SOS practice" },
  { id: "16", src: "/images/gallery/gallery-16.png", alt: "Coaching session with SOS players on the track" },
  { id: "17", src: "/images/gallery/gallery-17.png", alt: "703 Warriors players in lineup during training", featured: true },
  { id: "18", src: "/images/gallery/gallery-18.png", alt: "703 Warriors player on the field during practice", featured: true, layout: "tall" },
  { id: "19", src: "/images/gallery/gallery-19.png", alt: "Wide view of SOS community training session", featured: true, layout: "large" },
  { id: "20", src: "/images/gallery/gallery-20.png", alt: "Youth soccer practice with SOS mentors" },
  { id: "21", src: "/images/gallery/gallery-21.png", alt: "Group of SOS athletes on the soccer field" },
  { id: "22", src: "/images/gallery/gallery-22.png", alt: "Active training session with SOS youth players" },
  { id: "23", src: "/images/gallery/gallery-23.png", alt: "Players and coaches during SOS field session" },
  { id: "24", src: "/images/gallery/gallery-24.png", alt: "Community sports gathering with SOS participants" },
  { id: "25", src: "/images/gallery/gallery-25.png", alt: "Youth athletes practicing on the turf field" },
  { id: "26", src: "/images/gallery/gallery-26.png", alt: "SOS training moment with diverse young players" },
  { id: "27", src: "/images/gallery/gallery-27.png", alt: "Coaches addressing youth during SOS program" },
  { id: "28", src: "/images/gallery/gallery-28.png", alt: "Panoramic view of SOS community on the field", featured: true, layout: "wide" },
  { id: "29", src: "/images/gallery/gallery-29.png", alt: "Young player dribbling during SOS practice" },
  { id: "30", src: "/images/gallery/gallery-30.png", alt: "Team gathering with SOS coaches and athletes" },
  { id: "31", src: "/images/gallery/gallery-31.png", alt: "Outdoor SOS session with youth and mentors" },
  { id: "32", src: "/images/gallery/gallery-32.png", alt: "SOS team meeting with coach on the field" },
  { id: "33", src: "/images/gallery/gallery-33.png", alt: "Alexandria fire department visit at the SOS soccer field", featured: true, layout: "wide" },
  { id: "34", src: "/images/gallery/gallery-34.png", alt: "703 Warriors team huddle with coaches on the field", featured: true },
  { id: "35", src: "/images/gallery/gallery-35.png", alt: "Coach leading a youth training session on the grass" },
  { id: "36", src: "/images/gallery/gallery-36.png", alt: "Coaching moment with young players on the soccer field" },
  { id: "37", src: "/images/gallery/gallery-37.png", alt: "Soccer skills practice on the field" },
  { id: "38", src: "/images/gallery/gallery-38.png", alt: "SOS mentors on the field during a training session" },
  { id: "39", src: "/images/gallery/gallery-39.png", alt: "Coach on the soccer field during practice" },
  { id: "40", src: "/images/gallery/gallery-40.png", alt: "SOS program leaders coordinating on the field" },
  { id: "41", src: "/images/gallery/gallery-41.png", alt: "703 Warriors community gathering with youth athletes", featured: true, layout: "large" },
  { id: "42", src: "/images/gallery/gallery-42.png", alt: "Fire department community day with 703 Warriors players", featured: true },
  { id: "43", src: "/images/gallery/gallery-43.png", alt: "703 Warriors community event with families and mentors", featured: true },
  { id: "44", src: "/images/gallery/gallery-44.png", alt: "Youth soccer training session with SOS coaches" },
  { id: "45", src: "/images/gallery/gallery-45.png", alt: "703 Warriors team huddle on the field", featured: true, layout: "tall" },
  { id: "46", src: "/images/gallery/gallery-46.png", alt: "Team circle discussion during an SOS community session" },
  { id: "47", src: "/images/gallery/gallery-47.png", alt: "Community gathering under the trees at an SOS event" },
  { id: "48", src: "/images/gallery/gallery-48.png", alt: "703 Warriors coach addressing players during practice", featured: true, layout: "wide" },
  { id: "49", src: "/images/gallery/gallery-49.png", alt: "Young athletes during SOS field training" },
  { id: "50", src: "/images/gallery/gallery-50.png", alt: "SOS community sports program on the grass" },
  { id: "51", src: "/images/gallery/gallery-51.png", alt: "Youth players listening to coach instructions" },
  { id: "52", src: "/images/gallery/gallery-52.png", alt: "Team activity during SOS mentorship session" },
  { id: "53", src: "/images/gallery/gallery-53.png", alt: "703 Warriors players at outdoor practice" },
  { id: "54", src: "/images/gallery/gallery-54.png", alt: "Coaches and youth on the soccer field" },
  { id: "55", src: "/images/gallery/gallery-55.png", alt: "SOS training drills with young athletes" },
  { id: "56", src: "/images/gallery/gallery-56.png", alt: "Community gathering during SOS program event" },
  { id: "57", src: "/images/gallery/gallery-57.png", alt: "Youth soccer practice with mentors" },
  { id: "58", src: "/images/gallery/gallery-58.png", alt: "703 Warriors team moment on the field" },
  { id: "59", src: "/images/gallery/gallery-59.png", alt: "Outdoor coaching session with SOS participants" },
  { id: "60", src: "/images/gallery/gallery-60.png", alt: "Young players gathered for team instructions" },
  { id: "61", src: "/images/gallery/gallery-61.png", alt: "SOS community session with diverse athletes" },
  { id: "62", src: "/images/gallery/gallery-62.png", alt: "Active training on the grass field" },
  { id: "63", src: "/images/gallery/gallery-63.png", alt: "703 Warriors practice with coaches and players" },
  { id: "64", src: "/images/gallery/gallery-64.png", alt: "Team meeting during SOS field session" },
  { id: "65", src: "/images/gallery/gallery-65.png", alt: "Youth athletes during SOS community program" },
  { id: "66", src: "/images/gallery/gallery-66.png", alt: "SOS mentors leading outdoor sports activity" },
  { id: "67", src: "/images/gallery/gallery-67.png", alt: "703 Warriors players during team practice" },
  { id: "68", src: "/images/gallery/gallery-68.png", alt: "Community sports gathering with SOS youth" },
  { id: "69", src: "/images/gallery/gallery-69.png", alt: "Coaching session on the soccer field" },
  { id: "70", src: "/images/gallery/gallery-70.png", alt: "Young players in lineup during SOS training" },
  { id: "71", src: "/images/gallery/gallery-71.png", alt: "SOS program moment with coaches and athletes" },
  { id: "72", src: "/images/gallery/gallery-72.png", alt: "Team huddle during 703 Warriors practice" },
  { id: "73", src: "/images/gallery/gallery-73.png", alt: "Youth athletes practicing on the field" },
  { id: "74", src: "/images/gallery/gallery-74.png", alt: "SOS community training with diverse players" },
  { id: "75", src: "/images/gallery/gallery-75.png", alt: "703 Warriors event with families and mentors" },
  { id: "76", src: "/images/gallery/gallery-76.png", alt: "Outdoor SOS session with youth players" },
  { id: "77", src: "/images/gallery/gallery-77.png", alt: "Team gathering on the soccer field" },
  { id: "78", src: "/images/gallery/gallery-78.png", alt: "Young athletes during SOS mentorship" },
  { id: "79", src: "/images/gallery/gallery-79.png", alt: "703 Warriors community on the grass field" },
  { id: "80", src: "/images/gallery/gallery-80.png", alt: "SOS coaches addressing youth during practice" },
  { id: "81", src: "/images/gallery/gallery-81.png", alt: "Training session with 703 Warriors players" },
  { id: "82", src: "/images/gallery/gallery-82.png", alt: "Community circle during SOS program event" },
  { id: "83", src: "/images/gallery/gallery-83.png", alt: "Youth soccer moment with SOS mentors" },
  { id: "84", src: "/images/gallery/gallery-84.png", alt: "703 Warriors team practice outdoors" },
  { id: "85", src: "/images/gallery/gallery-85.png", alt: "SOS field session with young athletes" },
  { id: "86", src: "/images/gallery/gallery-86.png", alt: "Coaches and players during community event" },
  { id: "87", src: "/images/gallery/gallery-87.png", alt: "Youth gathering during SOS sports program" },
  { id: "88", src: "/images/gallery/gallery-88.png", alt: "703 Warriors training on the soccer field" },
  { id: "89", src: "/images/gallery/gallery-89.png", alt: "SOS community engagement with youth" },
  { id: "90", src: "/images/gallery/gallery-90.png", alt: "Team activity during outdoor practice" },
  { id: "91", src: "/images/gallery/gallery-91.png", alt: "Young players during SOS coaching session", featured: true },
  { id: "92", src: "/images/gallery/gallery-92.png", alt: "703 Warriors community sports gathering" },
  { id: "93", src: "/images/gallery/gallery-93.png", alt: "SOS mentors with youth on the field" },
  { id: "94", src: "/images/gallery/gallery-94.png", alt: "Outdoor team session with 703 Warriors", featured: true, layout: "wide" },
  { id: "95", src: "/images/gallery/gallery-95.png", alt: "Youth athletes at SOS community event" },
  { id: "96", src: "/images/gallery/gallery-96.png", alt: "Community program moment on the grass field" },
]

export const featuredGalleryImages = galleryImages.filter((image) => image.featured)
